// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Seneschal.Persistence.PostgreSql.Migrations;

[DbContext(typeof(PostgreSqlPersistenceDbContext))]
[Migration("202608010001_InitialEvaluationEvidence")]
partial class InitialEvaluationEvidence
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        PostgreSqlPersistenceDbContext.ConfigureModel(modelBuilder);
    }
}
